config/routes.rb
Rails.application.routes.draw do
  root "pages#index"
  get  "pages/privacy" => "pages#privacy"
  get '/sitemap', to: redirect("https://#{ENV['S3_BUCKET_NAME']}.s3-ap-northeast-1.amazonaws.com/sitemap.xml.gz")

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '*path', controller: 'application', action: 'render_404'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :redirect_root_domain
  before_action :ensure_domain

  rescue_from ActiveRecord::RecordNotFound, with: :render_404
  rescue_from ActionController::RoutingError, with: :render_404
  rescue_from Exception, with: :render_500

  def render_404
    render template: 'errors/error_404', status: 404, layout: 'application', content_type: 'text/html'
  end

  def render_500
    render template: 'errors/error_500', status: 500, layout: 'application', content_type: 'text/html'
  end

  private

  def redirect_root_domain
    return unless request.host === 'fullfii.com'
    redirect_to("#{request.protocol}www.fullfii.com#{request.fullpath}", status: 301)
  end

  FQDN = 'www.fullfii.com'

  # redirect correct server from herokuapp domain for SEO
  def ensure_domain
  return unless /\.herokuapp.com/ =~ request.host

  # 主にlocalテスト用の対策80と443以外でアクセスされた場合ポート番号をURLに含める 
  port = ":#{request.port}" unless [80, 443].include?(request.port)
  redirect_to "#{request.protocol}#{FQDN}#{port}#{request.path}", status: :moved_permanently
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    
  end

  def privacy

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_meta_tags
    {
      site: 'Fullfii',
      title: '知らない相手だからこそ、気楽に悩みを話せる',
      reverse: true,
      charset: 'utf-8',
      description: '～悩みを共感してほしいけど友達に話しても分かってもらえない方へ～同じ悩みを持つ方同士を結ぶ相談アプリ',
      keywords: '相談,共感,悩み',
      canonical: request.original_url,
      separator: '|',
      icon: [
        { href: image_url('44_44.png') },
        { href: image_url('284_284.png'), rel: 'apple-touch-icon', sizes: '180x180', type: 'image/jpg' },
      ],
      og: {
        site_name: :site,
        title: :title,
        description: :description,
        type: 'website',
        url: request.original_url,
        image: image_url('twitter_ogp.png'),
        local: 'ja-JP',
      },
      twitter: {
        card: 'summary',
        site: '@fullfiiOfficial',
        image: image_url('twitter_ogp.png'),
        width: 100,
        height: 100
      }
    }
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-GSGY49WT63"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-GSGY49WT63');
</script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= display_meta_tags(default_meta_tags)%>
    <meta name="google-site-verification" content="KJ4w8wgjaTLcJFpKFu5NO2kXMGORqBT9Hj-41pVf3Ok" />
  </head>

  <body>
    <%= yield %>
  </body>

</html>

app/views/pages/index.html.erb
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->

<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

</head>

<body>
<!-- header section -->
<section class="banner" role="banner">
  <header id="header">
    <div class="header-content clearfix"> 
      <%= link_to root_path do %>
        <%= image_tag "44_44.png", class: "logo"%>
      <%end%>
      <!-- navigation section  -->
      <nav class="navigation" role="navigation">
        <ul class="primary-nav">
          <li><%= link_to "トップページ", root_path %></li>
          <li><%= link_to "利用規約・プライバシーポリシー・特定商取引法に基づく表示", pages_privacy_path %></li>
          
        </ul>
      </nav>
      <a href="#" class="nav-toggle">Menu<span></span></a> </div>
    <!-- navigation section  --> 
  </header>
  <!-- banner text section-->
  <div id="banner" class="container">
    <div class="col-md-6 col-sm-12">
      <div class="banner-text ">
        <h1>知らない相手だからこそ、気楽に悩みを話せる</h1>
        <p>共感できる相手と繋がる相談アプリ</p>
        <div class="banner-btn"><%= image_tag 'apple_store_btn.png' %><%= image_tag 'google_store_btn.png' %></div>
      </div>
    </div>
    <div class="col-md-6 col-sm-12"> 
      <div class="banner-text">
        <%= image_tag 'stick_a_cheek.png', class: "banner-img img-responsive"%>
        </div>
      </div>
      <!-- banner text section--> 
  </div>
</section>
<!-- header section --> 
<!-- overview section -->
<section id="overview" class="section overview">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2 text-center">
        <h2 class="section-title">今話をきいてほしいけど、友達に話しづらいな...</h2>
        <p class="section-intro">時間が合わない、負担をかけたくない、共感してもらえない、ばらされないか心配などの理由で、友達に悩みを話しづらいと思うことがあると思います。そんな時、誰かに共感してほしい、すぐ誰かに聞いてほしいと思ったことありませんか？</div>

    </div>
  </div>
</section>

<!-- overview section --> 
<!-- feature section 1 -->
<section id="features" class="section features2">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2 text-center">
        <h2 class="section-title">誰かに話したい方同士を繋ぐ相談アプリ<span><ruby><rb>「fullfii」</rb><rp>（</rp><rt>フルフィー</rt><rp>）</rp></ruby></span></h2>
        <p class="section-intro">今すぐ誰かに話したい方、共感してほしい方を繋ぎ、すぐに悩みを話しあえる環境を作り出します</p>
      </div>
    </div>
    <div class="col-md-12 text-center overview-video">
        <iframe src="/videos/24673.t.mp4" controls frameborder="0" allowfullscreen > 
        </iframe>
      </div>
    <div class="row features1-content-space">
      <div class="col-md-4 col-sm-12">
        <div class="features1-content middle"> 
          <%= image_tag '1.png', class: "img-responsive"%>
                    <h4 class="text-center">相談内容は都度削除</h4>
        </div>
      </div>
      <div class="col-md-4 col-sm-12 "> 
        <div class="features1-content middle">
          <%= image_tag '2.png', class: "img-responsive"%>
                    <h4 class="text-center">チャットと電話（開発予定）対応</h4>
        </div>
      </div>
      <div class="col-md-4 col-sm-12">
        <div class="features1-content middle">
          <%= image_tag "same_sex.png", class: "img-responsive"%>
                    <h4 class="text-center">性別を選んで相談可</h4>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- feature section 1 --> 
<section id="features" class="section features1">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2 text-center">
        <h2 class="section-title">料金</h2>
                <p class="section-intro">料金プランは以下二つです。</p>
                <ul>
                <li><p class="section-intro">￥500 / 月 初回2週間は無料</p></li>
                <li><p class="section-intro">￥700 / 一ヶ月のみ</p></li>
                </ul>
      </div>
    </div>
    
  </div>
</section>

<!-- feature section 2 -->
<section id="features" class="section features2">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2 text-center">
        <h2 class="section-title">あなたに提供できる価値</h2>
        <p class="section-intro">相談するときに感じる壁はなんですか？Fullfiiならその壁を解決できるはずです</p>
      </div>
    </div>
    <div class="row features1-content-space">
      <div class="col-md-4 col-sm-12">
        <div class="features1-content middle"> 
          <h4>躊躇することなくすぐ話せる</h4>
          <p>友達に相談するときには「こんな夜遅くの時間にかけて迷惑かな...」「時間奪っちゃうの申し訳ないかな」と思うかもしれませんが、心配ありません。面識がないからこそ、変に気を使う必要がありません。軽い気持ちで相談できます。</p>
        </div>
      </div>
      <div class="col-md-4 col-sm-12 "> 
        <div class="features1-content middle">
          <h4>相談後を気にしなくてよい</h4>
          <p>話した内容は毎度アプリ上から削除されます。そのため、アプリ上で知らない人に話した内容が漏れることはありません。</p>
        </div>
      </div>
      <div class="col-md-4 col-sm-12">
        <div class="features1-content middle">
          <h4>共感してもらえる</h4>
          <p>特に恋愛で悩む方は解決策というより、同じ悩みを持つ人と話し、共感してもらいたいと思う方が多いかもしれません。同じ悩みを持つ人があなたの周りにいなくても、ここにはいるはずです。</p>
        </div>
      </div>
    </div>
    
    <div class="row features1-content-space">
      
      <div class="col-md-4 col-sm-12">
        <div class="features1-content middle"> 
          <h4>話すことで、スッキリする</h4>
          <p>友達に相談しようとしたが、時間が合わずまた別日に相談しようとする方は多いと思います。ただ、悩みを話すことで、話す前に比べてモヤモヤは晴れるはずです。少しでもポジティブな気分で明日を迎えることができるはずです。</p>
        </div>
      </div>
      <div class="col-md-4 col-sm-12 "> 
        <div class="features1-content middle">
          <h4>しっかり悩みを吐き出せる</h4>
          <p>1対1です。お互いに満足するまで話すことができます。</p>
        </div>
      </div>
      <div class="col-md-4 col-sm-12">
        <div class="features1-content middle">
          <p><%=image_tag("glasses_women.png")%></p>
        </div>
      </div>
      
    </div>
  </div>
</section>
<!-- feature section 2 --> 

<!-- feature section 3 -->
<section id="features" class="section features1">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2 text-center">
        <h2 class="section-title">fullfii特有の価値</h2>
        <p class="section-intro">既存の相談系アプリやサービスとの違い</p>
      </div>
      <div class="col-md-6">
        <div class="features2-content text-center">
          <h2 class="section-title">出会い系のマッチングアプリではない</h2>
          <p>相談する相手も性別を選択できます。同性のみにすれば知らない異性の方から、恋愛を目的とした連絡先の交換等はできません。</p>
        </div>
        
      </div>
      <div class="col-md-6"> <div class="features2-content text-center">
        <h2 class="section-title">相談内容は都度削除される</h2>
        <p>既存のチャットアプリや掲示板のように、悩みの内容が残り続けることはありません。</p>
      </div>
    </div>
    </div>
  </div>
</section>
<!-- feature section 3 --> 

<!-- screen shots slider section
<section id="screens" class="section screens">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2 text-center">
        <h2 class="section-title">ページのスクリーンショットの一部 </h2>
        <p class="section-intro"></p>
      </div>
    </div>
  </div>
  -->
  <!-- owl-carousel starts 
  <div id="owl-demo" class="owl-carousel">
    <div class="item"><img src="images/マイページ.png"></div>
    <div class="item"><img src="images/メッセージ送信画面.png"></div>
    <div class="item"><img src="images/検索画面.png"></div>
    <div class="item"><img src="images/手紙画面.png"></div>
    <div class="item"><img src="images/相談画面.png"></div>
    <div class="item"><img src="images/相談終了画面.png"></div>
    <div class="item"><img src="images/聞き上手一覧.png"></div>
    <div class="item"><img src="images/聞き上手選択画面.png"></div>

  </div>-->
  <!-- owl-carousel starts 
</section>--> 
<!-- screen shots slider section --> 

<!--subscribe section -->
<section id="download" class="section subscribe">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2 text-center">
        <h2>twitter登録宜しくお願いします！</h2>
        <p>ここまで読んでいただきありがとうございます。未だアプリは開発段階です。使いたいと思っていただいた方は、twitterの登録をお願いします。こういう機能が欲しい！など、意見、質問大歓迎です。より使いたいと思えるアプリとなるよう参考にさせていただきます。
        </p>
        <!-- <div  class="banner-btn"> <a href="#"><img src="images/apple-store-btn.png"></a> <a href="#" class="banner-btn"><img src="images/google-store-btn.png"></a></div> -->
        <div  class="banner-btn"><div class="banner-btn"><a href="https://twitter.com/fullfiiOfficial"><%= image_tag 'twitter.png' %></a> </div></div>
      </div>
    </div>
    <!-- <div class="row">
      <div class="col-md-6 col-md-offset-3 text-center subscribe-form">
        <h3 class="subscribe-title">Stay informed with our newsletter</h3> -->
        <!-- subscribe form 
        <form method="post" action="php/subscribe.php" name="subscribeform" id="subscribeform">
          <input type="text" name="email" placeholder="Enter your email address to get notified" id="subemail" />
          <input type="submit" name="send" value="Notify me" id="subsubmit" class="btn2" />
        </form>-->
        <!-- subscribe message 
        <div id="mesaj"></div>-->
        <!-- subscribe message  
      </div>-->
      <!-- subscribe form --> 
    </div>
  </div>
</section>
<!--subscribe section --> 

<!--contact section

<section id="contact" class="section text-center">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2 ">
        <h2 class="section-title">Get In Touch <span>Say Hello!</span></h2>
        <p class="section-intro">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae. </p>
      </div>
    </div> -->
    
    <!--contact form start
    <div class="col-md-6 col-md-offset-3 conForm">
      <div id="message"></div>
      <form method="post" action="php/contact.php" name="cform" id="cform">
        <input name="name" id="name" type="text" class="col-xs-12 col-sm-12 col-md-12 col-lg-12" placeholder="Your name..." >
        <input name="email" id="email" type="email" class=" col-xs-12 col-sm-12 col-md-12 col-lg-12 noMarr" placeholder="Email Address..." >
        <textarea name="comments" id="comments" cols="" rows="" class="col-xs-12 col-sm-12 col-md-12 col-lg-12" placeholder="Project Details..."></textarea>
        <input type="submit" id="submit" name="send" class="submitBnt" value="Send">
        <div id="simple-msg"></div>
      </form>
    </div>-->
    <!--contact form end
  </div>
</section>--> 

<!--contact section --> 
<!-- footer section-->
<footer class="section footer">
  <div class="footer-bottom">
    <div class="container">
      <div class="col-md-12">
        <p>
        <ul class="footer-share">
          <!--<li><a href="#"><i class="fa fa-facebook"></i></a></li>--> 
          <li><a href="https://twitter.com/fullfiiOfficial"><i class="fa fa-twitter"></i></a></li>
          <!--<li><a href="#"><i class="fa fa-instagram"></i></a></li>--> 
          <!--<li><a href="#"><i class="fa fa-youtube-play"></i></a></li>--> 
          <!--<li><a href="#"><i class="fa fa-vimeo"></i></a></li>--> 
        </ul>
        </p>
        <p>© Copyright © 2015 Rooky Inc. All Rights Reserved. Made with <i class="fa fa-heart pulse"></i> by <a href="http://www.designstub.com/">Designstub</a></p>
      </div>
    </div>
  </div>
</footer>
<!-- footer section--> 
<!-- Include JS files --> 

</body>
</html>